### PR TITLE
Add descriptive README

### PR DESCRIPTION
**Pull request by saswatamcode**
This PR adds a descriptive README for obsctl.

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
LGTM, can we add a small list with checkbox on what is open to add? e.g. support for logs and traces?

**Comment by saswatamcode** [comment]
Sure @periklis! Do you mean adding a checklist in a new issue or in the README itself? 🙂

**Comment by periklis** [comment]
> Sure @periklis! Do you mean adding a checklist in a new issue or in the README itself? slightly_smiling_face

I meant in the README.

**Review by periklis — APPROVED** [review]

**Review by matej-g — APPROVED** [review]
Nice :memo:

**Pull request merged**
